### 전체 이벤트 조회
GET http://localhost:8080/api/event
Content-Type: application/json

### 새로운 이벤트 추가
POST http://localhost:8080/api/event
Content-Type: application/json

{
  "id": 6,
  "dateTime": "2024-10-31T12:00:00",
  "title": "Event Title",
  "content": "Event Content",
  "eventType": "FESTIVAL",
  "userId": 1
}

### 특정 이벤트 수정
PUT http://localhost:8080/api/event/1
Content-Type: application/json

{
  "title": "Updated Event",
  "dateTime": "2024-11-01T15:00:00",
  "content": "이벤트 내용",
  "eventType": "FESTIVAL",
  "userId": 1
}

### 특정 이벤트 삭제
DELETE http://localhost:8080/api/event/1
Content-Type: application/json
