name: Validate PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check base branch
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "develop" ]; then
            echo "Pull requests to main must be from the develop branch."
            exit 1
          fi
